
    spring:
      datasource:
        url: jdbc:mysql://localhost:3306/user_management_db
        username: your-database-username
        password: your-database-password
      jpa:
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
